baseURL = 'http://edupy.gitpages.io/'
languageCode = 'es-co'
title = 'EduPy: Octubre 21 de 2.023, Cali, Colombia'
theme = 'arcana'
defaultcontentlanguage = "es"
[taxonomies]
    tag = "tags"

[params]
    description = "EduPy es el espacio para que docentes puedan usar herramientas de Python desde las aulas de clase."
    show_post_dates = false
    attribution = false
    countdownDate = "2023-10-21T08:00:00"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/slec-edu/edupy/"
    [[params.social]]
        title = "Youtube"
        icon = "fa-youtube"
        url = "https://www.youtube.com/@edupy_co"
    [[params.social]]
        title = "Lista de Correo"
        icon = "fa-paper-plane"
        url = "https://www.freelists.org/list/slec/"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"

    [params.footer]

        [[params.footer.links]]
            header = "Comunidades"
        [[params.footer.links.links]]
            title = "CaliDev"
            url = "https://calidev.co/"
        [[params.footer.links.links]]
            title = "Pyladies - Cali"
            url = "https://www.meetup.com/pyladies-co-cali/"
        [[params.footer.links.links]]
            title = "Tribu Latam"
            url = "https://www.tribulatam.com/"
        [[params.footer.links.links]]
            title = "SLEC"
            url = "https://www.slec.net/"        

        [[params.footer.links]]
            header = "Organizaciones"
        [[params.footer.links.links]]
            title = "FECTP"
            url = "https://www.fectp.org/"
        
        [[params.footer.links.links]]
            title = "UniLibre - Cali"
            url = "https://www.unilibre.edu.co/cali/"
        
        [[params.footer.links.links]]
            title = "Wikimedia Colombia"
            url = "https://co.wikimedia.org/"

        [[params.footer.links.links]]
            title = "Ubidots"
            url = "https://ubidots.com/"

        [[params.footer.links.links]]
            title = "Python Software Foundation"
            url = "python.org/psf"

        [params.footer.contact_form]
            enabled = false
            header = "Contáctanos"
            action = ""
